import type { NextPage } from 'next';
import { useContext } from 'react';
import AuthContext from './../contexts/authContext'
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
  const { session } = useContext(AuthContext);
  return (
    <div >
      <Head>
        <title>Bienvenido</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      </main>

      <footer >

      </footer>
    </div>
  );
};

export default Home;


// export const getServerSideProps: GetServerSideProps = async (context) => {
//   try {
//       const res1 = await fetch('/api/navbar', {
//           method: 'GET',
//       });

//       const res2 = await fetch('/api/brand', {
//           method: 'GET',
//       });

//       const items = await res1.json();
//       const brand = await res2.json();
//       return { props: { items, brand } }
//   } catch (err) {

//       return { props: { error: 'Something went wrong' } }
//   }
// }